name: ot_analysis
channels:
- conda-forge

dependencies:
- pip
- numpy>=1.21
- matplotlib
- pandas
- scipy
- pyqt
- qtpy
- pip:
    - supyr-struct
    - art
    - OT-Analysis
# conda-feedstock // conda-forge
